section-14-make-web-applications-in-python-using-django/django-1.11.2/mysite/books/urls.py
from django.conf.urls import url
from . import views,generic_views

app_name = "books"
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^(?P<id>[0-9]+)/$', views.detail, name="detail"),
    url(r'^$', views.index, name="add"),

    url(r'^generic$', generic_views.IndexView.as_view(), name='generic_index'),
    url(r'^generic/(?P<pk>[0-9]+)/$', generic_views.DetailView.as_view(), name='generic_detail'),
]

section-14-make-web-applications-in-python-using-django/django-1.11.2/mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^books/', include('books.urls')),
]

section-14-make-web-applications-in-python-using-django/django-1.11.2/mysite/books/models.py
from django.db import models


# python manage.py makemigrations
# python manage.py sqlmigrate books 0001
# python manage.py migrate
# python manage.py flush -> clear DB

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Book(models.Model):
    def __str__(self):
        return "[" + self.name + "]-[" + self.author + "]"

    name = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    price = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

section-14-make-web-applications-in-python-using-django/django-1.11.2/mysite/books/views.py
from django.http import HttpResponse, Http404
from django.template import loader
from .models import Book
from django.shortcuts import render


def index(request):
    all_books = Book.objects.all()
    context = {
        'all_books': all_books
    }
    return render(request, "books/index.html", context)


def detail(request, id):
    try:
        book = Book.objects.get(id=id)
    except Book.DoesNotExist:
        raise Http404("this book does not exist!")
    return render(request, "books/detail.html", {'book': book})

section-14-make-web-applications-in-python-using-django/django-1.11.2/mysite/books/templates/books/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <link rel="stylesheet" type="text/css" href="{% static 'books/style.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'books:index' %}">The Bookstore</a>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="">
                    <a href="{% url 'books:index' %}">
                        <span class="glyphicon glyphicon-book" aria-hidden="true"></span>&nbsp; Books
                    </a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="{% url 'books:add' %}">
                        <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>&nbsp; Add Book
                    </a>
                </li>
                <li class="">
                    <a href="{% url 'books:index' %}">
                        <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>

        </div>
    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

section-14-make-web-applications-in-python-using-django/django-1.11.2/mysite/books/templates/books/detail.html
{% extends 'books/base.html' %}

{% block title %}
    Detail page
{% endblock %}

{% block body %}
    <h1>{{ book.name }}</h1>
    <h3>{{ book.author }}</h3>
    <h4>{{ book.price }}</h4>
{% endblock %}

section-14-make-web-applications-in-python-using-django/django-1.11.2/mysite/books/templates/books/generic/detail.html
{% extends 'books/base.html' %}

{% block title %}
    Generic Detail page
{% endblock %}

{% block body %}
    <h1>{{ object.name }}</h1>
    <h3>{{ object.author }}</h3>
    <h4>{{ object.price }}</h4>
    <h4>{{ object.category_id }}</h4>
{% endblock %}

section-14-make-web-applications-in-python-using-django/django-1.11.2/mysite/books/templates/books/generic/index.html
{% extends 'books/base.html' %}

{% block title %}
    Generic Home page
{% endblock %}


{% block body %}
    <ul>
        {% for book in object_list %}
            <li><a href="{% url 'books:generic_detail' book.id %}">{{ book.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

section-14-make-web-applications-in-python-using-django/django-1.11.2/mysite/books/templates/books/index.html
{% extends 'books/base.html' %}

{% block title %}
    Home page
{% endblock %}


{% block body %}
    <ul>
        {% for book in all_books %}
            <li><a href="{% url 'books:detail' book.id %}">{{ book.name }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}